logging:
  level:
    root: debug

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: local
      database: review-local
      authentication-database: admin

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

external:
  naver-api:
    id: a
    secret: a
  github-api:
    client-id: a
    client-secret: a
    redirect-uri: http://localhost:8080/oauth2/callback/github
    scrop: "read:user user:email"